# Generated by Django 5.0.7 on 2024-08-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField(default=None, null=True)),
                ('temperature', models.IntegerField(default=None, null=True)),
                ('humidity', models.IntegerField(default=None, null=True)),
                ('noise', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
